#Author Nicolas Ostermann
# Verwende das offizielle MongoDB-Image als Basis
FROM mongo:latest

# Öffne den MongoDB-Port (standardmäßig 27017)
EXPOSE 27017

# Starte den MongoDB-Dienst beim Start des Containers
CMD ["mongod"]